### ISSUE TITLE
Wrong array shape when using single crosslink record

### ISSUE THREAD

**Issue by georgkempf** [lhatsk/AlphaLink#12]
Input with a single crosslink record is not reshaped properly at this line
https://github.com/lhatsk/AlphaLink/blob/0557e6fe2b281b3ae6ec43711ab43825cc9d0bd4/predict_with_crosslinks.py#L288

Instead of 
`    if len(links.shape) == 0:
        links = np.array([links])`
it should be
`    if len(links.shape) == 1:
        links = np.array([links])`

**Comment by lhatsk** [comment]
Thanks for pointing this out! It's fixed now.
