### ISSUE TITLE
CUDA stub file missing for cpu-only build

### ISSUE THREAD

**Issue by jgoodson** [lhatsk/AlphaLink#14]
The changes in https://github.com/lhatsk/AlphaLink/commit/c07ef5414b68ea684954cae8df2b4f0c942dfc34 to allow for container builds are missing the addition of the `openfold/utils/kernel/csrc/softmax_cuda_stub.cpp` file used for building the kernel present in the upstream OpenFold repo: https://github.com/aqlaboratory/openfold/blob/main/openfold/utils/kernel/csrc/softmax_cuda_stub.cpp. If this file is provided in the appropriate directory the build succeeds.

**Comment by lhatsk** [comment]
Thank you for pointing this out! I added the file.
