### ISSUE TITLE
Run "python preprocessing_distributions.py --infile restraints.csv" but get an error

### ISSUE THREAD

**Issue by chenx469** [lhatsk/AlphaLink#20]
Hi,

When I tried to get distance distributions from restraint lists by running "python preprocessing_distributions.py --infile restraints.csv", I received an error like below

$ python preprocessing_distributions.py --infile restraints.csv
Traceback (most recent call last):
  File "/lscratch/14291792/preprocessing_distributions.py", line 50, in <module>
    for line in restraints:
TypeError: iteration over a 0-d array

The restraints.csv is a test file and only has one line
12,135,15.0,5.0,normal

Could you let me know how to solve this problem?

Really appreciate!

Xiang

**Comment by lhatsk** [comment]
Thanks for reporting this! Should be fixed now.

**Comment by chenx469** [comment]
Thank you very much. It works now.

**Comment by lhatsk** [comment]
Sorry! Also fixed now...
