### ISSUE TITLE
Issue with multimer

### ISSUE THREAD

**Issue by samuelmurail** [lhatsk/AlphaLink#6]
Hello,

I have been trying using AlphaLink with distance constraints between different subunits.
From what I understand from the code, it doesn't seem possible to add such constraints.

Am I right ?

Cheers,
Samuel

**Comment by lhatsk** [comment]
Hi Samuel,

Yes, AlphaLink currently only works for single-chain proteins. Multimer is in the works.

Kolja

**Comment by avilella** [comment]
I'd be interested in using it for Multimer predictions/tuning as well.

**Comment by lhatsk** [comment]
We just released AlphaLink2 which can predict protein complexes: https://biorxiv.org/cgi/content/short/2023.06.07.544059v1

https://github.com/Rappsilber-Laboratory/AlphaLink2

The installation procedure will be a little more complicated. AlphaLink2 uses Uni-Fold and some memory optimisations.
